import { ElementInterface } from "../interfaces/element-interface";

export const elements: ElementInterface[] = [
    { id: 1, name: "Apple", description: "A sweet red fruit" },
    { id: 2, name: "Banana", description: "A long yellow fruit" },
    { id: 3, name: "Cherry", description: "A small red fruit" },
    { id: 4, name: "Date", description: "A sweet brown fruit" },
    { id: 5, name: "Elderberry", description: "A dark purple berry" },
    { id: 6, name: "Fig", description: "A soft purple fruit" },
    { id: 7, name: "Grape", description: "A small juicy fruit" },
    { id: 8, name: "Honeydew", description: "A sweet green melon" },
    { id: 9, name: "Indian Fig", description: "A type of prickly pear" },
    { id: 10, name: "Jackfruit", description: "A large tropical fruit" },
    { id: 11, name: "Kiwi", description: "A small brown fruit with green flesh" },
    { id: 12, name: "Lemon", description: "A sour yellow citrus fruit" },
    { id: 13, name: "Mango", description: "A sweet tropical fruit" },
    { id: 14, name: "Nectarine", description: "A smooth-skinned peach" },
    { id: 15, name: "Orange", description: "A round citrus fruit" },
    { id: 16, name: "Papaya", description: "A tropical fruit with orange flesh" },
    { id: 17, name: "Quince", description: "A yellow aromatic fruit" },
    { id: 18, name: "Raspberry", description: "A red berry with many drupelets" },
    { id: 19, name: "Strawberry", description: "A red heart-shaped fruit" },
    { id: 20, name: "Tangerine", description: "A small, sweet citrus fruit" },
    { id: 21, name: "Papaya", description: "A tropical fruit with orange flesh" },
    { id: 22, name: "Blueberry", description: "A small round blue fruit" },
    { id: 23, name: "Avocado", description: "A creamy green fruit with a large pit" },
    { id: 24, name: "Peach", description: "A juicy fruit with a soft skin" },
    { id: 25, name: "Plum", description: "A small, round, purple fruit" },
    { id: 26, name: "Pineapple", description: "A tropical fruit with a spiky skin" },
    { id: 27, name: "Apricot", description: "A small orange fruit with a smooth skin" },
    { id: 28, name: "Cantaloupe", description: "A sweet melon with orange flesh" },
    { id: 29, name: "Watermelon", description: "A large, juicy melon with green skin" },
    { id: 30, name: "Blackberry", description: "A small, dark purple fruit" },
    { id: 31, name: "Gooseberry", description: "A small, tart green fruit" },
    { id: 32, name: "Lychee", description: "A sweet tropical fruit with bumpy red skin" },
    { id: 33, name: "Papaya", description: "A tropical fruit with orange flesh" },
    { id: 34, name: "Dragonfruit", description: "A tropical fruit with pink skin and white flesh" },
    { id: 35, name: "Pomegranate", description: "A fruit with a thick skin and juicy red seeds" },
    { id: 36, name: "Mulberry", description: "A small, sweet dark fruit" },
    { id: 37, name: "Tamarind", description: "A tangy fruit with a pod-like shell" },
    { id: 38, name: "Fig", description: "A soft, sweet fruit with a wrinkled skin" },
    { id: 39, name: "Jackfruit", description: "A large tropical fruit with a spiky skin" },
    { id: 40, name: "Coconut", description: "A tropical fruit with a hard outer shell" },
    { id: 41, name: "Lime", description: "A small green citrus fruit" },
    { id: 42, name: "Tangerine", description: "A small, sweet citrus fruit" },
    { id: 43, name: "Soursop", description: "A sweet and sour fruit with spiky skin" },
    { id: 44, name: "Longan", description: "A small, round tropical fruit" },
    { id: 45, name: "Starfruit", description: "A tropical fruit with a star-shaped cross section" },
    { id: 46, name: "Cherimoya", description: "A creamy fruit with a sweet flavor" },
    { id: 47, name: "Custard Apple", description: "A sweet, creamy fruit" },
    { id: 48, name: "Rambutan", description: "A hairy fruit with a sweet flavor" },
    { id: 49, name: "Durian", description: "A large tropical fruit with a strong smell" },
    { id: 50, name: "Feijoa", description: "A sweet, aromatic fruit" },
    { id: 51, name: "Acerola", description: "A small, tart cherry-like fruit" },
    { id: 52, name: "Mamey", description: "A large tropical fruit with orange flesh" },
    { id: 53, name: "Dragonfruit", description: "A tropical fruit with bright pink skin" },
    { id: 54, name: "Passion Fruit", description: "A small, round fruit with a tangy flavor" },
    { id: 55, name: "Clementine", description: "A small, seedless orange" },
    { id: 56, name: "Prickly Pear", description: "A sweet fruit from a cactus plant" },
    { id: 57, name: "Litchi", description: "A small tropical fruit with a sweet flavor" },
    { id: 58, name: "Nashi Pear", description: "A crisp pear with a round shape" },
    { id: 59, name: "Pomelo", description: "A large citrus fruit with a thick skin" },
    { id: 60, name: "Kumquat", description: "A small citrus fruit with edible skin" },
    { id: 61, name: "Salak", description: "A tropical fruit with scaly skin" },
    { id: 62, name: "Langsat", description: "A sweet, sour fruit from Southeast Asia" },
    { id: 63, name: "Mangosteen", description: "A small round fruit with a sweet flavor" },
    { id: 64, name: "Mango", description: "A sweet tropical fruit" },
    { id: 65, name: "Ginger", description: "A spicy root often used in cooking" },
    { id: 66, name: "Yunnan Hackberry", description: "A small tropical fruit with a sweet flavor" },
    { id: 67, name: "Tamarillo", description: "A small, egg-shaped fruit with a tangy flavor" },
    { id: 68, name: "Nectarine", description: "A smooth-skinned peach" },
    { id: 69, name: "Goji Berry", description: "A small, red fruit often used in smoothies" },
    { id: 70, name: "Lemon", description: "A sour yellow citrus fruit" },
    { id: 71, name: "Mango", description: "A sweet tropical fruit" },
    { id: 72, name: "Pineapple", description: "A tropical fruit with spiky skin" },
    { id: 73, name: "Papaya", description: "A tropical fruit with orange flesh" },
    { id: 74, name: "Quince", description: "A yellow aromatic fruit" },
    { id: 75, name: "Coconut", description: "A tropical fruit with a hard outer shell" },
    { id: 76, name: "Passion Fruit", description: "A round tropical fruit with a tangy flavor" },
    { id: 77, name: "Blackberry", description: "A small, dark purple fruit" },
    { id: 78, name: "Cherry", description: "A small round red fruit" },
    { id: 79, name: "Plum", description: "A small round fruit" },
    { id: 80, name: "Apple", description: "A sweet red fruit" },
    { id: 81, name: "Raspberry", description: "A red berry with many drupelets" },
    { id: 82, name: "Strawberry", description: "A red heart-shaped fruit" },
    { id: 83, name: "Gooseberry", description: "A small, tart green fruit" },
    { id: 84, name: "Pomegranate", description: "A fruit with juicy red seeds" },
    { id: 85, name: "Date", description: "A sweet brown fruit" },
    { id: 86, name: "Kiwi", description: "A small brown fruit with green flesh" },
    { id: 87, name: "Tangerine", description: "A small citrus fruit" },
    { id: 88, name: "Honeydew", description: "A sweet green melon" },
    { id: 89, name: "Watermelon", description: "A large, juicy melon" },
    { id: 90, name: "Lychee", description: "A small tropical fruit with bumpy skin" },
    { id: 91, name: "Tamarind", description: "A tangy fruit with a pod-like shell" },
    { id: 92, name: "Dragonfruit", description: "A tropical fruit with pink skin and white flesh" },
    { id: 93, name: "Mulberry", description: "A small sweet fruit" },
    { id: 94, name: "Jackfruit", description: "A large tropical fruit" },
    { id: 95, name: "Peach", description: "A juicy fruit" },
    { id: 96, name: "Orange", description: "A round citrus fruit" },
    { id: 97, name: "Pineapple", description: "A tropical fruit" },
    { id: 98, name: "Lemon", description: "A yellow citrus fruit" },
    { id: 99, name: "Strawberry", description: "A red fruit" },
    { id: 100, name: "Apple", description: "A red fruit" },
    { id: 101, name: "Cantaloupe", description: "A melon with orange flesh" },
    { id: 102, name: "Plum", description: "A round fruit" },
    { id: 103, name: "Blueberry", description: "A small fruit" },
    { id: 104, name: "Grapefruit", description: "A tangy citrus fruit" },
    { id: 105, name: "Pear", description: "A sweet, crunchy fruit" },
    { id: 106, name: "Pomegranate", description: "A fruit with red seeds" },
    { id: 107, name: "Raspberry", description: "A small red fruit" },
    { id: 108, name: "Avocado", description: "A creamy green fruit" },
    { id: 109, name: "Papaya", description: "A tropical fruit" },
    { id: 110, name: "Coconut", description: "A hard-shelled tropical fruit" },
    { id: 111, name: "Tangerine", description: "A citrus fruit" },
    { id: 112, name: "Mango", description: "A tropical fruit" },
    { id: 113, name: "Lemon", description: "A yellow fruit" },
    { id: 114, name: "Strawberry", description: "A red fruit" },
    { id: 115, name: "Orange", description: "A round citrus fruit" },
    { id: 116, name: "Peach", description: "A juicy fruit" },
    { id: 117, name: "Grape", description: "A small fruit" },
    { id: 118, name: "Kiwi", description: "A brown fruit with green flesh" },
    { id: 119, name: "Watermelon", description: "A large fruit" },
    { id: 120, name: "Plum", description: "A small, round fruit" }
];
